version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    expose:
      - "6379"
  postgres:
    image: "postgres:alpine"
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    expose:
      - "5432"
