version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
  redis:
    image: 'redis:alpine'
    restart: 'always'
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:alpine"
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
